// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DataStore is an autogenerated mock type for the DataStore type
type DataStore struct {
	mock.Mock
}

// SetDocument provides a mock function with given fields: key, value, ctx
func (_m *DataStore) SetDocument(key string, value interface{}, ctx context.Context) error {
	ret := _m.Called(key, value, ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, context.Context) error); ok {
		r0 = rf(key, value, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
